# @package _global_
defaults:
  - /agents/practice/math_agent@agent
  - _self_

exp_id: "math_AIME24_smoke"

data:
  dataset: "AIME24_smoke"

concurrency: 3
pass_k: 1

verify_filename: "math.py"
verify_func_name: "verify_func"
